### PR TITLE
AMC now is ONE

### PR DESCRIPTION
**Pull request by cocka11**

### CODE REVIEW

**Comment by tattwamashi** [comment]
@cocka11 @sarthakroy2002 @minatiscape looks good to me but commit message is bit off


Shall i merge  or cancel pr and pick

**Comment by sarthakroy2002** [comment]
@ElectroPerf keep it on hold for further review

**Comment by afterallafk** [comment]
@cocka11 he is spammer he just creates pull request everwhere

**Comment by techyminati** [comment]
@cocka11 @cocka11 , we no longer merge PRs, please push it to our gerrit code review instead . Thanks

https://review.gerrithub.io/q/CipherOS

**Comment by cocka11** [comment]
not is spammer

**Pull request closed without merging**
